# Generated by Django 3.2.7 on 2022-11-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('comensales', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
