# Generated by Django 4.1.1 on 2022-10-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparacion',
            name='tiempo_preparacion',
            field=models.IntegerField(default=0),
        ),
    ]
