# Generated by Django 4.1.1 on 2022-10-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparaciones', '0004_preparacion_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparacion',
            name='Valor',
            field=models.IntegerField(default=0),
        ),
    ]
