# Generated by Django 4.1.1 on 2022-11-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Preparacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("stock", models.IntegerField(default=0)),
                ("activo", models.BooleanField()),
                ("receta", models.CharField(default="", max_length=255)),
                ("tiempo_preparacion", models.IntegerField(default=0)),
                ("Valor", models.IntegerField(default=0)),
                ("Imagen", models.ImageField(null=True, upload_to="preparaciones")),
            ],
        ),
    ]
