# Generated by Django 4.1.1 on 2022-11-19 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('stock', models.IntegerField(default=0)),
                ('activo', models.BooleanField()),
                ('receta', models.CharField(default='', max_length=255)),
                ('tiempo_preparacion', models.IntegerField(default=0)),
                ('Valor', models.IntegerField(default=0)),
                ('Imagen', models.ImageField(null=True, upload_to='preparaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idprep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preparaciones.preparacion')),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesas.mesa')),
            ],
        ),
    ]
