# Generated by Django 4.1.1 on 2022-10-10 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preparaciones', '0002_preparacion_tiempo_preparacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredientesPreparacion',
        ),
    ]
