# Generated by Django 4.1.1 on 2022-11-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparaciones', '0003_preparacion_valor_preparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparacion',
            name='utilidades',
            field=models.IntegerField(default=0),
        ),
    ]
