# Generated by Django 4.1.1 on 2022-10-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparaciones', '0003_delete_ingredientespreparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparacion',
            name='receta',
            field=models.CharField(default='', max_length=255),
        ),
    ]
