# Generated by Django 4.1.1 on 2022-10-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparaciones', '0005_preparacion_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparacion',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='preparaciones'),
        ),
    ]
