# Generated by Django 4.1.1 on 2022-11-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparaciones', '0006_preparacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparacion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
