# Generated by Django 4.1.1 on 2022-11-07 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0003_alter_mesa_numero_mesa'),
        ('preparaciones', '0007_alter_preparacion_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idprep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preparaciones.preparacion')),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesas.mesa')),
            ],
        ),
    ]
