# Generated by Django 4.1.1 on 2022-11-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("numero_Contacto", models.IntegerField()),
                ("email", models.CharField(default="", max_length=255)),
                ("Empresa", models.CharField(default="", max_length=255)),
                ("direccion", models.CharField(default="", max_length=100)),
            ],
        ),
    ]
