
# Generated by Django 4.1.1 on 2022-11-19 02:03


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('numero_Contacto', models.IntegerField(unique=True)),
                ('email', models.CharField(default='', max_length=255, unique=True)),
                ('Empresa', models.CharField(default='', max_length=255, unique=True)),
                ('direccion', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
