# Generated by Django 4.1.1 on 2022-11-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0002_proveedor_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='Empresa',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numero_Contacto',
            field=models.IntegerField(unique=True),
        ),
    ]
