# Generated by Django 4.1.1 on 2022-11-19 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega', '0001_initial'),
        ('preparaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientesPreparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ingrediente', models.IntegerField()),
                ('Preparacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preparaciones.preparacion')),
                ('ingrediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodega.producto')),
            ],
        ),
    ]
