# Generated by Django 4.1.1 on 2022-11-19 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        ('mesas', '0001_initial'),
        ('preparaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'pendiente'), ('PREPARANDO', 'preparando'), ('PREPARADO', 'preparado'), ('ENTREGADO', 'entregado')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('close', models.BooleanField(default=False)),
                ('Mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesas.mesa')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas.pago')),
                ('preparacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preparaciones.preparacion')),
            ],
        ),
    ]
