# Generated by Django 4.1.1 on 2022-11-22 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
        ('Proveedores', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedidosProveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadSolicitada', models.IntegerField()),
                ('cantidadRecibida', models.IntegerField(null=True)),
                ('valorSolicitado', models.IntegerField()),
                ('valorRecibido', models.IntegerField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('idProducto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodega.producto')),
                ('idProveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Proveedores.proveedor')),
            ],
        ),
    ]
