# Generated by Django 4.1.1 on 2022-10-24 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preparaciones', '0006_preparacion_imagen'),
        ('pedidos', '0002_alter_pedidos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'pendiente'), ('PREPARANDO', 'preparando'), ('PREPARADO', 'preparado'), ('ENTREGADO', 'entregado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='preparacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preparaciones.preparacion'),
        ),
    ]
