# Generated by Django 4.1.1 on 2022-09-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.CharField(choices=[('ADMINISTRADOR', 'administrador'), ('CLIENTE', 'cliente'), ('BODEGA', 'bodega'), ('COCINERO', 'cocinero'), ('GARZON', 'garzon'), ('FINANZAS', 'finanzas')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
