# Generated by Django 4.1.1 on 2022-10-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'pendiente'), ('PREPARANDO', 'preparando'), ('ENTREGADO', 'entregado')], max_length=255),
        ),
    ]
