# Generated by Django 4.1.1 on 2022-10-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='estado',
            field=models.CharField(default='Disponible', max_length=100),
        ),
    ]
