# Generated by Django 4.1.1 on 2022-10-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_alter_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='medida',
            field=models.CharField(default='', max_length=100),
        ),
    ]
