# Generated by Django 4.1.1 on 2022-11-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_producto_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='necesita_Stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
