# Generated by Django 4.1.1 on 2022-11-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_finanzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='finanzas',
            name='detalle',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
