# Generated by Django 4.1.1 on 2022-11-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_finanzas_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finanzas',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
